version: '3.4'
services:
  rabbitmq:
    image: rabbitmq:3.6-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=devuser
      - RABBITMQ_DEFAULT_PASS=devpass
      - RABBITMQ_DEFAULT_VHOST=devhost
